### ISSUE TITLE
gem 'comma' must be pinned to version 0.5.2

### ISSUE THREAD

**Issue by elijh** [Bettermeans/bettermeans#10]
The current Gemfile will grab a version that is incompatible with rails 2.x

**Comment by elf-pavlik** [comment]
hey @elijh , glad to see you've checked out bm =)
i have few branches here with various modifications on gitorious:
https://gitorious.org/bettermeans/bettermeans
soon i hope to start merging them here.... occupy.net there branch currently runs on https://collaborate.occupy.net/
oh, and please feel invited to jump in on #bettermeans - freenode!

**Comment by mockdeep** [comment]
Closing this.  Should be resolved in the current Gemfile, as it references the rails2 ref.
