### ISSUE TITLE
Bundle install fails Making capybara-webkit-1.1.1

### ISSUE THREAD

**Issue by berkes** [Bettermeans/bettermeans#11]
There is a bug in Capybara's OS support which makes it fail build on '0.1.1' https://github.com/thoughtbot/capybara-webkit/issues/208

Solution 1 is to omit the test group:

```
bundle install --without="test"
```

Solution 2, is to remove the pinning for cabybara-webkit version 1.1.x in `Gemfile` but instead have it install the latest version. This is the better solution, but right now requires quite some dependencies to be upgraded as well. The results of which are unknown to me.

**Comment by mockdeep** [comment]
It's now using capybara 1.1.2, so closing this.  Feel free to re-open if it's still a problem.
