### ISSUE TITLE
Bootstrap fails gem 'rails', '2.3.5' wants "mysql" not "mysql2"

### ISSUE THREAD

**Issue by berkes** [Bettermeans/bettermeans#12]
```
!!! The bundled mysql.rb driver has been removed from Rails 2.2. Please install the mysql gem and try again: gem install mysql.
rake aborted!
no such file to load -- mysql
```

changing "mysql2" to "mysql" solves this issue.

**Comment by mockdeep** [comment]
Is this still a problem?

**Comment by jsilence** [comment]
yes,

Installing on Ubuntu 10.04. with ruby 1.8.

Installation has been an unpleasant hassle anyway and now I'm stuck with the above error.

berkes wrote "changing "mysql2" to "mysql" solves this issue. "  but _where_?

**Comment by berkes** [comment]
I changed that in the Gemfile.

**Comment by mockdeep** [comment]
I'll take a look and see if I can fix this in the next few days.  Looks like this pull might resolve it:

https://github.com/Bettermeans/bettermeans/pull/19

**Comment by jsilence** [comment]
Managed to fix it and went on with the install.

**Comment by mockdeep** [comment]
Alright, this should now be fixed.  Let me know if it's still causing a problem.
