### ISSUE TITLE
App cannot start "uninitialized constant ActiveSupport::Dependencies::Mutex" incompatibility between rubygems and rails version.

### ISSUE THREAD

**Issue by berkes** [Bettermeans/bettermeans#13]
http://stackoverflow.com/questions/5176782/uninitialized-constant-activesupportdependenciesmutex-nameerror#5412085

Updating to latest 2.3.x version helps:

`Gemfile:`

`gem 'rails', '~> 2.3.5' (Will install 2.3.14)`

`config/environment.rb`:
`RAILS_GEM_VERSION = '2.3.14' unless defined? RAILS_GEM_VERSION`

This aint very clean, because it requires you to go into environment.rb everytime you run `gem update` and Rails gets updated to some new dot-release.

**Comment by mockdeep** [comment]
Rails has been updated to the latest version.  Closing this issue for now.
