### ISSUE TITLE
Unevaluated variables in strings

### ISSUE THREAD

**Issue by toupeira** [Bettermeans/bettermeans#17]
- On summary screen: "#{notifications} waiting for you"
- Notification title: "New role: #{role_name}"
- Notification text: "You are now a #{role_name} of..."
- In time distances: "#{count} minutes ago", "#{count} hours ago", "#{count} days ago", "#{count} years ago"
- On story history (in the fullscreen view): "#{label} changed from #{old} to #{new}", "#{label} set to #{value}", "#{label} deleted (#{old})"

**Comment by mockdeep** [comment]
Woops.  My bad.  This format is deprecated, but I guess we need to update the gems before switching the interpolation.

**Comment by mockdeep** [comment]
And fixed.

**Comment by toupeira** [comment]
Thanks!
