### ISSUE TITLE
BetterMeans account activation email just arrived.

### ISSUE THREAD

**Issue by PaddyPatPat** [Bettermeans/bettermeans#23]
Hello, 

Just wondering if anyone else has just received an account activation email from administrator@bettermeans.com?

Link doesn't seem to work but it is quite out of the blue so I thought I'd enquire.

**Comment by mockdeep** [comment]
Sorry, I just enabled the email queue on my domain, better.boon.gl, so if you signed up there your registration email went through.

**Comment by PaddyPatPat** [comment]
Ahh very good. I wondered if it was from your domain but the URL suggested the main BetterMeans site, hence my question. Thanks for clarifying.

**Comment by mockdeep** [comment]
Yeah, I need to go through and clean up the url references next.
