### ISSUE TITLE
Seg Fault in Memoizable

### ISSUE THREAD

**Issue by imw** [Bettermeans/bettermeans#6]
So, I'm trying to install an instance of bettermeans on a VPS.
The Mongrel log looks like this:

*\* Daemonized, any open files are closed.  Look at log/mongrel.pid and log/mongrel.log for info.
*\* Starting Mongrel listening at 0.0.0.0:12001
*\* Starting Rails with production environment...
/usr/lib/ruby/gems/1.8/gems/actionpack-2.3.5/lib/action_controller/mime_type.rb:80: warning: already initialized constant JPG
/usr/lib/ruby/gems/1.8/gems/actionpack-2.3.5/lib/action_controller/mime_type.rb:80: warning: already initialized constant PNG
/usr/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/memoizable.rb:32: [BUG] Segmentation fault
ruby 1.8.7 (2011-02-18 patchlevel 334) [x86_64-linux]

Do you think that you might be able to help me resolve this issue?
It would be greatly appreciated.

**Comment by elf-pavlik** [comment]
can you try running it on VPS with more RAM?

**Comment by mockdeep** [comment]
Closing.  Feel free to re-open if you're still having issues.
